### ISSUE TITLE
null

### ISSUE THREAD

**Issue by jonataspinto** [felipuus/Doe-sangue#1]
voltou???

**Comment by Brenont** [comment]
`<p> voltou? </p>`

**Comment by felipuus** [comment]
voltei kkk

**Comment by jonataspinto** [comment]
voltou?? tu levou 11 dias para responder.. :smile:

**Comment by jonataspinto** [comment]
@Brenont fala para ele! `tem que ter atividade no github todo dia.`

**Comment by Brenont** [comment]
Hahaha um passo de cada vez

**Comment by jonataspinto** [comment]
bom saber que voltou @felipuus nos procure no whats.. é bom manter contato!
